// The Sprint Builder — the operating system that makes organic scalable.
// Every finding becomes a task with a dollar value (when computable), an effort
// size, and its Forge artifact attached. Rank by value-per-hour, pack greedily
// into whatever hours budget the operator actually has this week.

const EFFORT_HOURS = { S: 0.5, M: 2, L: 6 };
const SEV_BASE = { critical: 900, warning: 350, opportunity: 120, pass: 0 };

const EFFORT_BY_FORGE = { titles: 'S', schema: 'S', links: 'S', redirects: 'S', brief: 'L' };
const PAID_EFFORT = { smart_bidding: 'S', broad_match: 'S', budget_pacing: 'S', wasted_spend: 'M', conversion_tracking: 'M', ad_relevance: 'M', geo_targeting: 'S', account_structure: 'L' };

// paid audit findings -> sprint tasks. Dollar value is read straight off the
// finding's own evidence (any *_micros monthly-ish figure), never invented.
export function paidFindingToTask(f) {
  if (f.severity === 'pass') return null;
  let value = 0;
  const scan = (obj) => {
    for (const [k, v] of Object.entries(obj || {})) {
      if (typeof v === 'number' && /micros/.test(k)) value = Math.max(value, Math.round(v / 1e6));
      else if (v && typeof v === 'object' && !Array.isArray(v)) scan(v);
    }
  };
  scan(f.evidence?.result);
  const effort = PAID_EFFORT[f.category] || 'M';
  const hours = EFFORT_HOURS[effort];
  const val = value || SEV_BASE[f.severity] || 100;
  return {
    id: `paid:${f.category}`, pillar: 'paid', category: f.category,
    severity: f.severity, title: f.title, do_this: f.recommendation,
    effort, hours, value_month: value || null, priority: val / hours,
    fix: null, recheck_days: 14, audit_link: true,
  };
}

export function buildHolisticTasks({ organicFindings = [], paidFindings = [] }) {
  const organic = buildTasks(organicFindings);
  const paid = paidFindings.map(paidFindingToTask).filter(Boolean);
  return [...organic, ...paid].sort((a, b) => b.priority - a.priority);
}
const CHECK_DAYS = { titles: 14, schema: 10, links: 21, brief: 28, redirects: 7, default: 21 };

export function buildTasks(findings) {
  const tasks = [];
  for (const f of findings) {
    if (f.severity === 'pass') continue;
    const effort = f.fix ? (EFFORT_BY_FORGE[f.fix.forge] || 'M') : 'M';
    const value = Math.round(f.value_month || 0) || SEV_BASE[f.severity] || 100;
    const hours = EFFORT_HOURS[effort];
    tasks.push({
      id: `${f.pillar}:${f.category}`,
      pillar: f.pillar,
      category: f.category,
      severity: f.severity,
      title: f.title,
      do_this: f.recommendation,
      effort,
      hours,
      value_month: f.value_month ? Math.round(f.value_month) : null,
      priority: value / hours,
      fix: f.fix || null,
      recheck_days: f.fix ? (CHECK_DAYS[f.fix.forge] || CHECK_DAYS.default) : CHECK_DAYS.default,
    });
  }
  return tasks.sort((a, b) => b.priority - a.priority);
}

export function packSprint(tasks, hoursBudget = 4) {
  const sprint = []; let used = 0;
  for (const t of tasks) {
    if (used + t.hours <= hoursBudget + 0.01) { sprint.push(t); used += t.hours; }
    if (used >= hoursBudget) break;
  }
  return { sprint, hours_used: Math.round(used * 10) / 10, hours_budget: hoursBudget, backlog: tasks.filter((t) => !sprint.includes(t)) };
}

export function sprintMarkdown({ sprint, hours_used, hours_budget }, siteUrl) {
  const lines = [
    `## Search sprint — ${siteUrl?.replace(/^https?:\/\//, '') || 'site'}`,
    `${sprint.length} tasks · ~${hours_used}h of a ${hours_budget}h budget · generated by Clarify Savant`,
    '',
  ];
  sprint.forEach((t, i) => {
    lines.push(`${i + 1}. **${t.title}**${t.value_month ? ` — ~$${t.value_month.toLocaleString()}/mo at stake` : ''} _(effort ${t.effort}, ~${t.hours}h)_`);
    if (t.do_this) lines.push(`   - Do: ${t.do_this}`);
    lines.push(`   - Verify: re-check in Search Console in ${t.recheck_days} days`);
  });
  return lines.join('\n');
}
